sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lmkertesz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lmkertesz/docker-react npm run test